import type { Metadata } from 'next'
import { Inter, Dosis } from 'next/font/google'
import './globals.css'
import Header from './components/headerItems/Header'
import Sidebar from './components/sidebarItems/Sidebar'

const inter = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Youtube',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='grid grid-cols-2 w-100 max-h-screen overflow-hidden'>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
