import type { Metadata } from 'next'
import { Inter, Dosis } from 'next/font/google'
import './globals.css'
import { Providers } from './Provider';
import { Toaster } from 'react-hot-toast';
import Header from './components/headerItems/Header';

const inter = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Youtube',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
